# Generated by Django 4.1.7 on 2023-03-30 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_calculator_alter_post_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculator',
            name='price',
            field=models.IntegerField(default=25),
        ),
    ]
